tests:
  - any: ["mollie/*_tests.go", "mollie/connect/*_tests.go", "mollie/tools/*_tests.go"]

documentation:
  - docs/*

docker:
  - any: ["Dockerfile", ".dockerignore"]

gh-actions:
  - .github/**/*.yml

core:
  - any: ["mollie/*.go", "!mollie/*_tests.go", "!mollie/tools/*"]

modules:
  - go.*  

testdata:
  - testdata/*

config:
  - any: [".*.yml"]

meta-files:
  - any: ["Makefile", "README.md", "LICENSE", "SECURITY.md"]

tools:
  - any: ["mollie/tools/*.go"]
