tests:
  - any: ["mollie/*_test.go", "mollie/connect/*_test.go", "mollie/tools/*_test.go"]

documentation:
  - any: ["docs/*"]

docker:
  - any: ["Dockerfile", ".dockerignore"]

devcontainers:
  - any: [".devcontainer/*"]

gh-actions:
  - any: [".github/**/*.yml"]

core:
  - any: ["mollie/*.go", "!mollie/*_tests.go", "!mollie/tools/*"]

modules:
  - any: ["go.*"]

testdata:
  - any: ["testdata/*"]

config:
  - any: [".*.yml"]

meta-files:
  - any: ["Makefile", "README.md", "LICENSE", "SECURITY.md"]

tools:
  - any: ["mollie/tools/*.go"]
