# This is an example goreleaser.yaml file with some sane defaults.
project_name: mollie-api-golang
builds:
  skip: true
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs"
      - "^changelog"
      - "Merge pull request^"