# This is an example goreleaser.yaml file with some sane defaults.
project_name: mollie-api-golang
build:
  skip: true
changelog:
  sort: desc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - 'changelog'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
