name: "Check docs links"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/documentation-links.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/documentation-links.yml"

jobs:
  linkChecker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: |
            report
            automated-issue
            help-wanted
          assignees: VictorAvelar
