name: "Check docs links"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/documentation-links.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/documentation-links.yml"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          output: json

      # - name: Create Issue From File
      #   if: env.lychee_exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v4
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
