name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, master]
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: golangci-lint
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          workdir: mollie
          only-new-issues: true
